common:
  ws_server: "ws://127.0.0.1:6701"
  ws_token: ""
  nickname:
    - "ゆき酱"
  command_prefix: "/"
  super_users:
    - 1227427929
config:
  seturepo: "./config/seturepo.yaml"
data:
  chess: "./data/chess/chess.db"
  bilibili: "./data/bilibili/bilibili.db"
  blacklist: "./data/blacklist/blacklist.db"
temp:
  chess: "./temp/chess"
