rootdir: ./data/imgsave
repos:
  - - 新田慧海
    - 新田恵海
    - 慧海
    - 恵海
    - えみ
    - emi
  - - 高坂穗乃果
    - 高坂穂乃果
    - 穗乃果
    - 穂乃果
    - ほのか
    - honoka
  - - 表情包
blacklist:
  - 1781924496
  - 2802340025
  - 847988306
